
baseurl = "https://ricardoferreira.site"
title = "Ricardo Ferreira"

theme = "hugo-coder"

languagecode = "pt-br"
defaultcontentlanguage = "pt-br"

googleAnalytics = "UA-151634076-1"

paginate = 5

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourdiscussshortname"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# posts - it should rename to same name of content folder
[permalinks]
  blog = "/:year/:month/:slug/"

[params.adsense]
 client = "ca-pub-5245300802542741"
 inArticleSlot = "3200652252"
 graficosSlot = "6376166852"

# opens external links absolute links in a new window or tab.
# Blackfriday is a Markdown processor implemented in Go.
[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[params]
    author = "Ricardo Ferreira"
    description = "More than ten years of expertise in IT, I am passionate about new technologies, bachelor's Computer Science. Nowadays, I keep learning new skills in Data Engineer"
    keywords = "linux,docker,sysadmin,bussiness intelligence,bi,data science,datascience,technology"
    info = "Senior Infrastructure and Open source IT"
    avatarurl = "images/perfil-02.jpeg"
    #gravatar = "john.doe@example.com"
    footercontent = "Built using Hugo v0.76.5. Hosted by Netlify."

    # OG_IMAGE
    images = ["coverpage-FACEBOOK.png"]

    dateformat = "2 January 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = ["scss/custom.scss"]

    # Custom JS
    customJS = []

    ctaToHome = "More about me"

# If you want to use fathom(https://usefathom.com) for analytics, add this section
[params.fathomAnalytics]
    siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
[params.plausibleAnalytics]
    domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
[params.goatCounter]
    code = "code"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/ricardoferreiracosta08"
[[params.social]]
    name = "Instagram"
    icon = "fa fa-instagram"
    weight = 3
    url = "https://www.instagram.com/ricardoferreira.tec"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 4
    url = "https://twitter.com/rferreira_tec"
#[[params.social]]
#    name = "YouTuBe"
#    icon = "fa fa-youtube"
#    weight = 5
#    url = "https://youtube.com/c/RicardoFerreiraTecnologia"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/ricardo-ferreira-costa"
#[[params.social]]
#    name = "Medium"
#    icon = "fa fa-medium"
#    weight = 5
#    url = "https://medium.com/@ricardoferreiracosta"
#[[params.social]]
#    name = "Telegram"
#    icon = "fa fa-telegram"
#    weight = 6
#    url = "https://t.me/ricardoferreira_tec"

[params.rss]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 7
    url = "https://ricardoferreira.site/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

[[params.curso]]
   name = "Aprender a aprender: foco na área de TI"
   icon = "/images/cover-aprender-aprender-TI.png"
   link = "https://bit.ly/cursoAprender-aprender-TI"
   desc = "Aprenda técnicas de aprendizagem que irão potencializar seus estudos e tirar você de um ciclo ineficiente de aprendizado"
   bgcolor = "#035482"
   textcolor = "white"
   linecolor = "#035482"

[[params.curso]]
   name = "Maratona Infraestrutura Open Source"
   icon = "/images/cover-maratona.png"
   link = "https://ricardoferreira.ck.page/aulas-gratuitas"
   desc = "Aprenda de maneira objetiva e prática tópicos da Infraestrutura dentro de uma comunidade com mais de 200 membros"
   bgcolor = "#d76b0a"
   textcolor = "black"
   linecolor = "#d76b0a"

[[params.curso]]
   name = "Docker do zero: Introdução a administração de containers"
   icon = "/images/cover-docker-udemy.png"
   link = "http://bit.ly/cursoAprendaDockerdoZero"
   desc = "Aprenda Docker do zero e seja eficiente na entrega dos serviços de TI usando tecnologia de containers"
   bgcolor = "darkblue"
   textcolor = "white"
   linecolor = "darkblue"

[languages]
    [languages.en]
        languagename = "English"
        LanguageDirection = "images/en32.png"

        [languages.en.menu]

#            [[languages.en.menu.main]]
#            name = "About"
#            weight = 1
#            url = "about/"

            [[languages.en.menu.main]]
            name = "Hi! Would like talk with me?"
            weight = 1
            url = "https://t.me/ricardoferreiracosta"
            pre = "<i class='fa fa-comment'></i>"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"
            pre = "<i class='fa fa-pencil'></i>"

#            [[languages.en.menu.main]]
#            name = "Projects"
#            weight = 3
#            url = "projects/"

#            [[languages.en.menu.main]]
#            name = "All my courses online"
#            weight = 3
#            pre = "<i class='fa fa-book'></i>"
#            url = "https://www.udemy.com/user/ricardo-ferreira-costa-2/"

#            [[languages.en.menu.main]]
#            name = "Contact me"
#            weight = 5
#            url = "contact/"


    [languages.pt-br]
        languagename = "Português"
        title = "Ricardo Ferreira"
        LanguageDirection = "../images/br32.png"

        [languages.pt-br.params]
            author = "Ricardo Ferreira"
            info = "Linux · Infraestrutura · Dados"
	    description = "Apaixonado por novas tecnologias, Bacharel em Ciência da Computação. Alguns anos na operação, decidi mirar os dados."
            keywords = "linux,docker,bpm,dados,bussiness intelligence,bi,sysadmin, tecnologia"
            footercontent = "Construído usando Hugo v0.76.5. Hospedado em Netlify"
            ctaToHome = "Mais sobre mim"

        [languages.pt-br.menu]

            [[languages.pt-br.menu.main]]
            name = "Opa! Afim de trocar uma ideia?"
            weight = 1
            url = "https://t.me/ricardoferreiracosta"
            post = "shake"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "blog/"

#            [[languages.pt-br.menu.main]]
#            name = "Meus cursos online"
#            weight = 3
#            url = "cursos/"

#            [[languages.pt-br.menu.main]]
#            name = "Mentoria Gratuita | Agende a sua"
#            weight = 5
#            pre = "<i class='fa fa-calendar'></i>"
#            url = "https://calendly.com/ricardoferreira_tec/mentoriagratuita"
#            post = "shake"

#            [[languages.pt-br.menu.main]]
#            name = "Maratona Infraestrutura Open Source | Inscreva-se"
#            pre = "/images/cover-maratona.png"
#            identifier = "Acervo de gravações de aulas transmitidas ao vivo. Mais de 20 horas de conteúdo objetivo e prático de tópicos da Infraestrutura Open Source. Além disso, espaço para entrar numa comunidade focada. 2 Aulas novas por mês!!"
#            weight = 5
#            url = "https://ricardoferreira.ck.page/aulas-semanais"
#            url = "https://ricardoferreira.ck.page/aulas-gratuitas"
#            post = "shake"

#            [[languages.pt-br.menu.main]]
#            name = "Bootcamp Infraestrutura Open Source"
#            weight = 6
#            url = "https://bootcampinfraestrutura.carrd.co/"
#            post = "shake"


# https://bootcampinfraestrutura.carrd.co/
